# Generated by cucumber-sinatra. (2012-02-23 12:12:42 -0600)

ENV['RACK_ENV'] = 'test'

require File.join(File.dirname(__FILE__), '..', '..', 'lib/stag.rb')
require File.join(File.dirname(__FILE__), '..', '..', 'lib/server/server.rb')

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Stag::Server

class StagWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  StagWorld.new
end

begin
  require 'database_cleaner'
  require 'database_cleaner/cucumber'
  DatabaseCleaner.strategy = :truncation
rescue NameError
  raise "You need to add database_cleaner to your Gemfile (in the :test group) if you wish to use it."
end